# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [3]:
# Load the data
df = pd.read_csv("AviationData.csv", encoding="latin1")

C:\Users\USER\AppData\Local\Temp\ipykernel_22364\395179125.py:2: DtypeWarning: Columns (0: Latitude, 1: Longitude, 2: Broad.phase.of.flight) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("AviationData.csv", encoding="latin1")

In [4]:
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [5]:
df.shape

(88889, 31)

In [6]:
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  str
 1   Investigation.Type      88889 non-null  str
 2   Accident.Number         88889 non-null  str
 3   Event.Date              88889 non-null  str
 4   Location                88837 non-null  str
 5   Country                 88663 non-null  str
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  str
 9   Airport.Name            52704 non-null  str
 10  Injury.Severity         87889 non-null  str
 11  Aircraft.damage         85695 non-null  str
 12  Aircraft.Category       32287 non-null  str
 13  Registration.Number     87507 non-null  str
 14  Make                    88826 non-null  str
 15  Model                   88797 non-null  str
 16  Amateur.Built           88787 non-null  str
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  str
 19  FAR.Description         32023 non-null  str
 20  Schedule                12582 non-null  str
 21  Purpose.of.flight       82697 non-null  str
 22  Air.carrier             16648 non-null  str
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  str
 28  Broad.phase.of.flight   61724 non-null  str
 29  Report.Status           82505 non-null  str
 30  Publication.Date        75118 non-null  str
dtypes: float64(5), object(2), str(24)
memory usage: 38.9+ MB

In [9]:
df.isnull().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

In [10]:
df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [11]:
df["Aircraft.Category"].value_counts(dropna=False)

Aircraft.Category
NaN                  56602
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64

In [12]:
df["Amateur.Built"].value_counts(dropna=False)

Amateur.Built
No     80312
Yes     8475
NaN      102
Name: count, dtype: int64

In [13]:
df["Event.Date"].head()

0    1948-10-24
1    1962-07-19
2    1974-08-30
3    1977-06-19
4    1979-08-02
Name: Event.Date, dtype: str

In [15]:
df["Event.Date"] = pd.to_datetime(df["Event.Date"], errors="coerce")

In [16]:
df["Event.Date"].dtype

dtype('<M8[us]')

In [17]:
df = df[df["Event.Date"] >= "1983-01-01"]

In [18]:
df.shape

(85289, 31)

In [19]:
df = df[df["Aircraft.Category"] == "Airplane"]

In [20]:
df.shape

(24441, 31)

In [21]:
df = df[df["Amateur.Built"] == "No"]

In [22]:
df.shape

(21447, 31)

In [23]:
df.isnull().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                      6
Country                       1
Latitude                   2278
Longitude                  2284
Airport.Code               7464
Airport.Name               7377
Injury.Severity             813
Aircraft.damage            1227
Aircraft.Category             0
Registration.Number         206
Make                          3
Model                        18
Amateur.Built                 0
Number.of.Engines          2551
Engine.Type                3956
FAR.Description             480
Schedule                  18926
Purpose.of.flight          3680
Air.carrier               11285
Total.Fatal.Injuries       2750
Total.Serious.Injuries     2828
Total.Minor.Injuries       2544
Total.Uninjured             711
Weather.Condition          2979
Broad.phase.of.flight     18619
Report.Status              4663
Publication.Date            957
dtype: int64

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

In [24]:
df["Injury.Severity"].value_counts(dropna=False)

Injury.Severity
Non-Fatal      16318
Fatal           3603
NaN              813
Minor            146
Incident         115
Fatal(1)         115
Serious          108
Fatal(2)          87
Fatal(3)          28
Fatal(4)          25
Unavailable       16
Fatal(5)          15
Fatal(6)          11
Fatal(7)          10
Fatal(10)          6
Fatal(8)           5
Fatal(12)          3
Fatal(13)          2
Fatal(154)         2
Fatal(11)          1
Fatal(17)          1
Fatal(27)          1
Fatal(16)          1
Fatal(54)          1
Fatal(160)         1
Fatal(97)          1
Fatal(125)         1
Fatal(228)         1
Fatal(9)           1
Fatal(18)          1
Fatal(169)         1
Fatal(131)         1
Fatal(24)          1
Fatal(20)          1
Fatal(65)          1
Fatal(19)          1
Fatal(26)          1
Fatal(113)         1
Name: count, dtype: int64

In [25]:
df["Aircraft.damage"].value_counts(dropna=False)

Aircraft.damage
Substantial    16990
Destroyed       2316
NaN             1227
Minor            817
Unknown           97
Name: count, dtype: int64

In [26]:
df[[
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured"
]].isnull().sum()

Total.Fatal.Injuries      2750
Total.Serious.Injuries    2828
Total.Minor.Injuries      2544
Total.Uninjured            711
dtype: int64

In [27]:
df[[
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured"
]].dtypes

Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
dtype: object

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [28]:
df["Total.People"] = (
    df["Total.Fatal.Injuries"].fillna(0)
    + df["Total.Serious.Injuries"].fillna(0)
    + df["Total.Minor.Injuries"].fillna(0)
    + df["Total.Uninjured"].fillna(0)
)

In [29]:
df["Fatal.Serious.Injuries"] = (
    df["Total.Fatal.Injuries"].fillna(0)
    + df["Total.Serious.Injuries"].fillna(0)
)

In [30]:
df["Fatal.Serious.Fraction"] = (
    df["Fatal.Serious.Injuries"]
    / df["Total.People"].replace(0, np.nan)
)

In [31]:
df[[
    "Total.People",
    "Fatal.Serious.Injuries",
    "Fatal.Serious.Fraction"
]].head()

      Total.People  Fatal.Serious.Injuries  Fatal.Serious.Fraction
4149         588.0                     0.0                     0.0
4150         588.0                     0.0                     0.0
4171           2.0                     2.0                     1.0
4285           5.0                     1.0                     0.2
5957         289.0                     0.0                     0.0

In [32]:
df["Fatal.Serious.Fraction"].describe()

count    20543.000000
mean         0.283971
std          0.431704
min          0.000000
25%          0.000000
50%          0.000000
75%          0.800000
max          1.000000
Name: Fatal.Serious.Fraction, dtype: float64

In [33]:
df["Fatal.Serious.Fraction"].isnull().sum()

np.int64(904)

In [34]:
df.loc[
    df["Fatal.Serious.Fraction"].isnull(),
    ["Total.Fatal.Injuries", "Total.Serious.Injuries",
     "Total.Minor.Injuries", "Total.Uninjured"]
].head(10)

,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
29591,NaN,NaN,NaN,NaN
41656,NaN,NaN,NaN,NaN
42287,NaN,NaN,NaN,NaN
42613,NaN,NaN,NaN,NaN
42847,NaN,NaN,NaN,NaN
43298,NaN,NaN,NaN,NaN
43648,NaN,NaN,NaN,NaN
43788,NaN,NaN,NaN,NaN
43804,NaN,NaN,NaN,NaN
44014,NaN,NaN,NaN,NaN

In [35]:
df.columns.tolist()

['Event.Id',
 'Investigation.Type',
 'Accident.Number',
 'Event.Date',
 'Location',
 'Country',
 'Latitude',
 'Longitude',
 'Airport.Code',
 'Airport.Name',
 'Injury.Severity',
 'Aircraft.damage',
 'Aircraft.Category',
 'Registration.Number',
 'Make',
 'Model',
 'Amateur.Built',
 'Number.of.Engines',
 'Engine.Type',
 'FAR.Description',
 'Schedule',
 'Purpose.of.flight',
 'Air.carrier',
 'Total.Fatal.Injuries',
 'Total.Serious.Injuries',
 'Total.Minor.Injuries',
 'Total.Uninjured',
 'Weather.Condition',
 'Broad.phase.of.flight',
 'Report.Status',
 'Publication.Date',
 'Total.People',
 'Fatal.Serious.Injuries',
 'Fatal.Serious.Fraction']

In [36]:
df["Total.People"].isnull().sum()

np.int64(0)

In [37]:
(df["Total.People"] == 0).sum()

np.int64(904)

In [38]:
df["Total.People"].value_counts(dropna=False).head(10)

Total.People
1.0    9062
2.0    6740
3.0    1642
4.0    1098
0.0     904
5.0     348
6.0     207
7.0     141
8.0      70
9.0      66
Name: count, dtype: int64

In [39]:
df["Fatal.Serious.Fraction"] = (
    df["Fatal.Serious.Injuries"]
    / df["Total.People"].replace(0, float("nan"))
)

In [40]:
df["Fatal.Serious.Fraction"].isnull().sum()

np.int64(904)

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [41]:
df["Aircraft.damage"].value_counts(dropna=False)

Aircraft.damage
Substantial    16990
Destroyed       2316
NaN             1227
Minor            817
Unknown           97
Name: count, dtype: int64

In [42]:
df["Aircraft.damage"] = df["Aircraft.damage"].str.strip().str.title()

In [43]:
df["Aircraft.Destroyed"] = df["Aircraft.damage"].eq("Destroyed")

In [44]:
df[["Aircraft.damage", "Aircraft.Destroyed"]].head(10)

     Aircraft.damage  Aircraft.Destroyed
4149           Minor               False
4150           Minor               False
4171       Destroyed                True
4285             NaN               False
5957           Minor               False
5960       Destroyed                True
6669             NaN               False
6760           Minor               False
6806     Substantial               False
7084     Substantial               False

In [46]:
df["Aircraft.Destroyed"].value_counts(dropna=False)

Aircraft.Destroyed
False    19131
True      2316
Name: count, dtype: int64

In [47]:
df.loc[
    df["Aircraft.Destroyed"],
    "Aircraft.damage"
].value_counts(dropna=False)

Aircraft.damage
Destroyed    2316
Name: count, dtype: int64

In [49]:
df["Aircraft.damage"].isnull().sum()

np.int64(1227)

In [50]:
df["Aircraft.Destroyed"] = df["Aircraft.damage"].map({
    "Destroyed": True,
    "Substantial": False,
    "Minor": False
})

In [51]:
df["Aircraft.Destroyed"].value_counts(dropna=False)

Aircraft.Destroyed
False    17807
True      2316
NaN       1324
Name: count, dtype: int64

In [52]:
df.groupby(
    "Aircraft.damage",
    dropna=False
)["Aircraft.Destroyed"].value_counts(dropna=False)

Aircraft.damage  Aircraft.Destroyed
Destroyed        True                   2316
Minor            False                   817
Substantial      False                 16990
Unknown          NaN                      97
NaN              NaN                    1227
Name: count, dtype: int64

In [53]:
df["Aircraft.Destroyed"] = df["Aircraft.damage"].map({
    "Destroyed": True,
    "Substantial": False,
    "Minor": False
})

In [54]:
df["Aircraft.Destroyed"].value_counts(dropna=False)

Aircraft.Destroyed
False    17807
True      2316
NaN       1324
Name: count, dtype: int64

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [55]:
df["Make"].value_counts().head(10)

Make
CESSNA                4867
PIPER                 2803
Cessna                2279
Piper                 1186
BOEING                1037
BEECH                 1018
Beech                  413
MOONEY                 238
Boeing                 227
CIRRUS DESIGN CORP     218
Name: count, dtype: int64

In [56]:
df["Make"].isnull().sum()

np.int64(3)

In [57]:
df["Make"].unique()[:30]

<ArrowStringArray>
[                     'Lockheed',                        'Boeing',
                         'Piper',                  'De Havilland',
                       'Douglas',                'Short Brothers',
                         'Beech',                        'Cessna',
                    'Swearingen',                          'Lake',
                       'Grumman',                        'Mooney',
                    'Gulfstream',                         'Helio',
              'Airbus Industrie',                       'Univair',
                         'Maule',                   'Taylorcraft',
                         'Globe',                       'Embraer',
 'Consolidated Aeronautics Inc.',             'Mcdonnell Douglas',
                      'Bellanca',                        'Fokker',
                'Aero Commander',                         'Ayres',
             'Grumman-schweizer',                'Britten-norman',
                       'Learjet',         'Saab-scania Ab (saab)']
Length: 30, dtype: str

In [58]:
df["Make"].str.contains(r"^\s|\s$", na=False).sum()

np.int64(0)

Cleaning Tasks for the Make Column

The following cleaning tasks will be performed on the "Make" column:

1. Handle missing values: Identify missing aircraft make records and determine how to handle them without introducing incorrect information.
2. Remove extra spaces: Remove leading and trailing spaces from aircraft make names.
3. Standardize capitalization: Convert aircraft make names to a consistent format.
4. Check for inconsistent entries: Inspect the values for spelling differences and inconsistent naming.
5. Verify the cleaning: Check the unique values and missing-value count after cleaning.

In [59]:
# Remove leading and trailing spaces
df["Make"] = df["Make"].str.strip()

# Standardize capitalization
df["Make"] = df["Make"].str.title()

In [60]:
df["Make"].value_counts().head(10)

Make
Cessna                7146
Piper                 3989
Beech                 1431
Boeing                1264
Mooney                 363
Airbus                 243
Cirrus Design Corp     220
Bellanca               219
Air Tractor Inc        219
Maule                  215
Name: count, dtype: int64

In [61]:
df["Make"].isnull().sum()

np.int64(3)

In [62]:
df["Make"].unique()[:30]

<ArrowStringArray>
[                     'Lockheed',                        'Boeing',
                         'Piper',                  'De Havilland',
                       'Douglas',                'Short Brothers',
                         'Beech',                        'Cessna',
                    'Swearingen',                          'Lake',
                       'Grumman',                        'Mooney',
                    'Gulfstream',                         'Helio',
              'Airbus Industrie',                       'Univair',
                         'Maule',                   'Taylorcraft',
                         'Globe',                       'Embraer',
 'Consolidated Aeronautics Inc.',             'Mcdonnell Douglas',
                      'Bellanca',                        'Fokker',
                'Aero Commander',                         'Ayres',
             'Grumman-Schweizer',                'Britten-Norman',
                       'Learjet',         'Saab-Scania Ab (Saab)']
Length: 30, dtype: str

In [63]:
# Remove leading and trailing spaces
df["Make"] = df["Make"].str.strip()

# Standardize capitalization
df["Make"] = df["Make"].str.title()

In [64]:
df["Make"].isnull().sum()

np.int64(3)

In [65]:
df["Make"].str.contains(r"^\s|\s$", na=False).sum()

np.int64(0)

In [66]:
df["Make"].nunique()

1087

In [67]:
df["Make"].str.lower().nunique()

1087

In [68]:
df["Make"].isnull().sum()

np.int64(3)

In [69]:
df["Make"].str.contains(r"^\s|\s$", na=False).sum()

np.int64(0)

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [71]:
df["Model"].head(10)

4149               L-1011
4150                  747
4171            PA-28-140
4285                DHC-6
5957             DC-10-10
5960    LEARSTAR, L-18-56
6669               SD3-30
6760              727-200
6806                  C35
7084                 180K
Name: Model, dtype: str

In [73]:
df["Model"].isnull().sum()

np.int64(18)

In [74]:
df = df.dropna(subset=["Model"]).copy()

In [75]:
df["Model"].isnull().sum()

np.int64(0)

In [76]:
df["Model"].value_counts()

Model
172          772
737          403
152          317
182          304
172S         278
            ...
P206D          1
PHANTOM        1
KITFOX S5      1
M-8 EAGLE      1
PA-44          1
Name: count, Length: 3553, dtype: int64

In [77]:
df["Model"].value_counts().head(10)

Model
172     772
737     403
152     317
182     304
172S    278
PA28    273
SR22    265
172N    250
180     213
A36     189
Name: count, dtype: int64

In [78]:
df["Model"].value_counts()

Model
172          772
737          403
152          317
182          304
172S         278
            ...
P206D          1
PHANTOM        1
KITFOX S5      1
M-8 EAGLE      1
PA-44          1
Name: count, Length: 3553, dtype: int64

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [79]:
df["Engine.Type"].dtype

In [80]:
df["Engine.Type"].isnull().sum()

np.int64(3943)

In [81]:
df["Engine.Type"].value_counts(dropna=False)

Engine.Type
Reciprocating      15014
NaN                 3943
Turbo Prop          1251
Turbo Fan            926
Turbo Jet            133
Unknown              133
Geared Turbofan       12
Turbo Shaft           11
Electric               5
UNK                    1
Name: count, dtype: int64

In [82]:
df["Engine.Type"].unique()

<ArrowStringArray>
[      'Turbo Fan',   'Reciprocating',      'Turbo Prop',       'Turbo Jet',
               nan,         'Unknown',     'Turbo Shaft',        'Electric',
 'Geared Turbofan',             'UNK']
Length: 10, dtype: str

In [83]:
df["Weather.Condition"].isnull().sum()

np.int64(2970)

In [84]:
df["Weather.Condition"].value_counts(dropna=False)

Weather.Condition
VMC    17082
NaN     2970
IMC     1068
Unk      215
UNK       94
Name: count, dtype: int64

In [92]:
df["Weather.Condition"].unique()

<ArrowStringArray>
['VMC', 'IMC', 'UNK', nan, 'Unk']
Length: 5, dtype: str

In [93]:
df["Number.of.Engines"].isnull().sum()

np.int64(2547)

In [94]:
df["Number.of.Engines"].value_counts(dropna=False)

Number.of.Engines
1.0    15734
2.0     3004
NaN     2547
4.0       93
3.0       40
0.0        9
8.0        1
6.0        1
Name: count, dtype: int64

In [95]:
df["Number.of.Engines"].dtype

dtype('float64')

In [96]:
df["Purpose.of.flight"].isnull().sum()

np.int64(3671)

In [97]:
df["Purpose.of.flight"].value_counts(dropna=False)

Purpose.of.flight
Personal                     11713
NaN                           3671
Instructional                 2753
Aerial Application             933
Business                       498
Unknown                        374
Positioning                    349
Skydiving                      164
Aerial Observation             161
Other Work Use                 155
Flight Test                    120
Ferry                          103
Executive/corporate            103
Banner Tow                      89
Public Aircraft - Federal       52
Air Race show                   48
Public Aircraft                 39
Glider Tow                      35
Public Aircraft - State         24
Firefighting                    17
Public Aircraft - Local         12
ASHO                             5
Air Race/show                    4
Air Drop                         3
PUBS                             3
External Load                    1
Name: count, dtype: int64

In [99]:
df["Purpose.of.flight"].unique()

<ArrowStringArray>
[                  'Unknown',                         nan,
                  'Personal',                 'Skydiving',
        'Aerial Application',               'Positioning',
             'Instructional',                  'Business',
           'Public Aircraft',                     'Ferry',
            'Other Work Use',        'Aerial Observation',
       'Executive/corporate', 'Public Aircraft - Federal',
             'Air Race/show',               'Flight Test',
   'Public Aircraft - State',                'Glider Tow',
                'Banner Tow',              'Firefighting',
             'External Load',             'Air Race show',
   'Public Aircraft - Local',                  'Air Drop',
                      'PUBS',                      'ASHO']
Length: 26, dtype: str

In [100]:
df["Broad.phase.of.flight"].value_counts(dropna=False)

Broad.phase.of.flight
NaN            18607
Landing         1255
Takeoff          509
Cruise           264
Approach         234
Maneuvering      167
Taxi             111
Go-around         89
Descent           73
Climb             58
Standing          47
Unknown           12
Other              3
Name: count, dtype: int64

In [101]:
df["Broad.phase.of.flight"].unique()

<ArrowStringArray>
[   'Standing',        'Taxi',      'Cruise',       'Other',       'Climb',
     'Takeoff',     'Landing',    'Approach', 'Maneuvering',     'Descent',
           nan,   'Go-around',     'Unknown']
Length: 13, dtype: str

Inspection and Potential Cleaning Tasks

1. Engine.Type: Check for missing values, inconsistent formatting, and unexpected engine categories.
2. Weather.Condition: Check for missing values, inconsistent capitalization, extra spaces, and unexpected weather categories.
3. Number.of.Engines: Check for missing values, unexpected numerical values, and appropriate data types.
4. Purpose.of.flight: Check for missing values, inconsistent category names, and unexpected entries.
5. Broad.phase.of.flight: Check for missing values, inconsistent formatting, and unexpected flight-phase categories.

Cleaning will be performed only where the inspection identifies a genuine issue. Missing values will be handled carefully to avoid introducing incorrect information.

In [102]:
df["Engine.Type"].value_counts(dropna=False)

Engine.Type
Reciprocating      15014
NaN                 3943
Turbo Prop          1251
Turbo Fan            926
Turbo Jet            133
Unknown              133
Geared Turbofan       12
Turbo Shaft           11
Electric               5
UNK                    1
Name: count, dtype: int64

In [103]:
df["Engine.Type"].unique()

<ArrowStringArray>
[      'Turbo Fan',   'Reciprocating',      'Turbo Prop',       'Turbo Jet',
               nan,         'Unknown',     'Turbo Shaft',        'Electric',
 'Geared Turbofan',             'UNK']
Length: 10, dtype: str

In [104]:
df["Engine.Type"] = df["Engine.Type"].replace({
    "uknown":"uknown"
})

In [105]:
df["Engine.Type"].value_counts(dropna=False)

Engine.Type
Reciprocating      15014
NaN                 3943
Turbo Prop          1251
Turbo Fan            926
Turbo Jet            133
Unknown              133
Geared Turbofan       12
Turbo Shaft           11
Electric               5
UNK                    1
Name: count, dtype: int64

Cleaning Tasks for Engine.Type

1. Identify missing values in the column.
2. Correct spelling errors in engine-type categories.
3. Standardize inconsistent category labels.
4. Preserve valid engine types.
5. Verify the column after cleaning.

In [106]:
df["Engine.Type"] = df["Engine.Type"].replace({
    "Uknown": "Unknown",
    "Unk": "Unknown"
})

In [107]:
df["Engine.Type"].value_counts(dropna=False)

Engine.Type
Reciprocating      15014
NaN                 3943
Turbo Prop          1251
Turbo Fan            926
Turbo Jet            133
Unknown              133
Geared Turbofan       12
Turbo Shaft           11
Electric               5
UNK                    1
Name: count, dtype: int64

In [108]:
df["Weather.Condition"].value_counts(dropna=False)

Weather.Condition
VMC    17082
NaN     2970
IMC     1068
Unk      215
UNK       94
Name: count, dtype: int64

In [109]:
df["Weather.Condition"].isnull().sum()

np.int64(2970)

In [110]:
df["Weather.Condition"].unique()

<ArrowStringArray>
['VMC', 'IMC', 'UNK', nan, 'Unk']
Length: 5, dtype: str

Cleaning Tasks for Weather.Condition

1. Identify missing values in the column.
2. Inspect weather-condition categories for spelling errors.
3. Remove unnecessary spaces from category names.
4. Standardize capitalization where necessary.
5. Check for inconsistent or duplicate category labels.
6. Verify the column after cleaning.

In [111]:
df["Weather.Condition"] = (
    df["Weather.Condition"]
    .str.strip()
    .str.title()
)

In [112]:
df["Weather.Condition"].value_counts(dropna=False)

Weather.Condition
Vmc    17082
NaN     2970
Imc     1068
Unk      309
Name: count, dtype: int64

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [113]:
df.isnull().sum().sort_values(ascending=False)

Schedule                  18915
Broad.phase.of.flight     18607
Air.carrier               11276
Airport.Code               7454
Airport.Name               7369
Report.Status              4654
Engine.Type                3943
Purpose.of.flight          3671
Weather.Condition          2970
Total.Serious.Injuries     2821
Total.Fatal.Injuries       2745
Number.of.Engines          2547
Total.Minor.Injuries       2538
Longitude                  2275
Latitude                   2269
Aircraft.Destroyed         1322
Aircraft.damage            1225
Publication.Date            955
Fatal.Serious.Fraction      901
Injury.Severity             811
Total.Uninjured             706
FAR.Description             480
Registration.Number         204
Location                      6
Country                       1
Make                          1
Event.Id                      0
Accident.Number               0
Investigation.Type            0
Aircraft.Category             0
Event.Date                    0
Model                         0
Amateur.Built                 0
Fatal.Serious.Injuries        0
Total.People                  0
dtype: int64

In [114]:
missing_percent = (df.isnull().mean() * 100).sort_values(ascending=False)
print(missing_percent)

Schedule                  88.268235
Broad.phase.of.flight     86.830930
Air.carrier               52.620281
Airport.Code              34.784638
Airport.Name              34.387979
Report.Status             21.718232
Engine.Type               18.400299
Purpose.of.flight         17.130991
Weather.Condition         13.859723
Total.Serious.Injuries    13.164403
Total.Fatal.Injuries      12.809744
Number.of.Engines         11.885762
Total.Minor.Injuries      11.843763
Longitude                 10.616454
Latitude                  10.588455
Aircraft.Destroyed         6.169210
Aircraft.damage            5.716552
Publication.Date           4.456578
Fatal.Serious.Fraction     4.204583
Injury.Severity            3.784591
Total.Uninjured            3.294601
FAR.Description            2.239955
Registration.Number        0.951981
Location                   0.027999
Country                    0.004667
Make                       0.004667
Event.Id                   0.000000
Accident.Number            0.000000
Investigation.Type         0.000000
Aircraft.Category          0.000000
Event.Date                 0.000000
Model                      0.000000
Amateur.Built              0.000000
Fatal.Serious.Injuries     0.000000
Total.People               0.000000
dtype: float64

In [115]:
df[["Amateur.Built", "Fatal.Serious.Injuries", "Total.People"]].isnull().sum()

Amateur.Built             0
Fatal.Serious.Injuries    0
Total.People              0
dtype: int64

In [116]:
df[["Amateur.Built", "Fatal.Serious.Injuries", "Total.People"]].isnull().sum()

Amateur.Built             0
Fatal.Serious.Injuries    0
Total.People              0
dtype: int64

In [117]:
(df.isnull().mean() * 100).sort_values(ascending=False).head(10)

Schedule                  88.268235
Broad.phase.of.flight     86.830930
Air.carrier               52.620281
Airport.Code              34.784638
Airport.Name              34.387979
Report.Status             21.718232
Engine.Type               18.400299
Purpose.of.flight         17.130991
Weather.Condition         13.859723
Total.Serious.Injuries    13.164403
dtype: float64

In [119]:
df = df.drop(columns=[
    "Schedule",
    "Broad.phase.of.flight",
    "Air.carrier"
])

In [120]:
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Purpose.of.flight', 'Total.Fatal.Injuries', 'Total.Serious.Injuries',
       'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition',
       'Report.Status', 'Publication.Date', 'Total.People',
       'Fatal.Serious.Injuries', 'Fatal.Serious.Fraction',
       'Aircraft.Destroyed'],
      dtype='str')

In [122]:
(df.isnull().mean() * 100).sort_values(ascending=False).head(10)

Airport.Code              34.784638
Airport.Name              34.387979
Report.Status             21.718232
Engine.Type               18.400299
Purpose.of.flight         17.130991
Weather.Condition         13.859723
Total.Serious.Injuries    13.164403
Total.Fatal.Injuries      12.809744
Number.of.Engines         11.885762
Total.Minor.Injuries      11.843763
dtype: float64

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [123]:
df.to_csv("cleaned_aviation_data.csv", index=False)

In [124]:
import os
print(os.path.exists("cleaned_aviation_data.csv"))

True